# config for dotnet-releaser
[msbuild]
project = "grpc-curl.sln"
# Make the tool faster by compiling all references together
properties.PublishReadyToRunComposite = true
[github]
user = "xoofx"
repo = "grpc-curl"