name: ci

env:
  PROJECT_NAME: GrpcCurl
  LIB_NAME: DynamicGrpc

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'changelog.md'
    - 'readme.md'
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build & test (Release)
      run: dotnet test src -c Release

    - name: Coveralls
      run: dotnet test src -c Release -f net6.0 /p:Include=\"[${{env.LIB_NAME}}]*\" /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

    #- name: Coveralls Upload
    #  uses: coverallsapp/github-action@v1.0.1
    #  if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    #  with:
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
    #    path-to-lcov: src/${{env.PROJECT_NAME}}.Tests/coverage.info

    - name: Pack
      run: |
          dotnet pack src -c Release

    - name: Publish
      if: github.event_name == 'push'
      run: |
          if ( "${{github.ref}}" -match "^refs/tags/[0-9]+\.[0-9]+\.[0-9]+" ) {
              dotnet nuget push src\**\*.nupkg -s nuget.org -k ${{secrets.NUGET_TOKEN}}
          } else {
              echo "publish is only enabled by tagging with a release tag"
          }
